name: fixnum_csq
version: 1.0.1
description: >-
  Library for 32- and 64-bit signed fixed-width integers with consistent
  behavior between native and JS runtimes.
repository: https://github.com/ContentSquare/fixnum/

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
